version: "3.8"

services:
  postgres:
    image: postgres:13
    user: ${DB_USER:-postgres}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
      POSTGRES_DB: ${DB_NAME:-animal}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432/tcp"
    expose:
      - 5432
    networks:
      - animal
    restart: on-failure
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  animal:
    driver: bridge

volumes:
  postgres:
    driver: local
