### GET all dogs on the server
GET http://localhost:8000/pet/cat
Accept: application/json

### Create new dog position
POST http://localhost:8000/pet/cat
Content-Type: application/json

{
  "name": "Tom",
  "description": "The sphynx is a medium-sized cat with a striking appearance, identified by her hairless, wrinkled skin and large ears. She has a sleek, muscular body that is dense and heavy for her size. The breed is medium sized but nicely muscled.",
  "breed": "sphynx",
  "weight": 4.4,
  "birthday": "2022-05-02",
  "sex": "male",
  "tailLength": 30,
  "color": "gray",
  "woolType": "short",
  "isChipped": true
}